### ISSUE TITLE
Preparar material sobre software libre para el primer día

### ISSUE THREAD

**Issue by JJ** [JJ/doctorado-ciencia-abierta#1]
Básicamente se trata de explicar licencias y cómo se pueden usar para liberar software y contenido. Puedes usar alguna charla de @psicobyte

**Comment by Makova** [comment]
Pensaba que Pablo estaría en este curso :(

**Comment by JJ** [comment]
Pablo está en el de Git y LaTeX...

**Comment by Makova** [comment]
Entonces, ¿que doy yo, días y horario?. Supongo que si es Git puedo meter directamente el repo de la OSL sobre Git, y sobre Licencias algo de Pablo que tenga en su web.

**Comment by JJ** [comment]
Está en el fichero de contenido, descárgate el repo. Tú estarías el primer día, próximo jueves.

**Comment by Makova** [comment]
Ok. El primer día jueves les doy Git y como abrirse una cuenta en GitHub. Me he descargado el repo por ssh, pero no hay fichero de contenido, o no lo veo.

**Comment by Makova** [comment]
Vaya, acabas de subirlo.

**Comment by JJ** [comment]
Son dos horas, enséñale como poner issues en GitHub, como establecer hitos,
como hacer pull requests, como resolver conflictos... Todo eso.

**Comment by Makova** [comment]
Subida presentación de Licencias y hoy terminaré la de software libre y demás.
