### ISSUE TITLE
Duda sobre la entrega de actividades

### ISSUE THREAD

**Issue by segura2010** [JJ/doctorado-ciencia-abierta#3]
Buenos días @JJ ,

El 15 de diciembre le escribimos un email con la entrega de actividades del curso, pero no hemos recibido respuesta. Nos gustaría saber si recibió correctamente el email y si todo es correcto.

Somos el grupo del proyecto de Evaluación de coches; el Github es: https://github.com/gejujoal/CarEvaluation2018.

Un saludo

**Comment by JJ** [comment]
Siento no haber contestado. Ya entregué las notas y yo creo que deberían
estar ya los certificados disponibles.

**Comment by segura2010** [comment]
@JJ ok! Gracias JJ :)

Nos ha extrañado porque tampoco hemos recibido ningún email de posgrado con los certificados ni nada. Por eso pensabamos que igual había habido algún problema con el email.

**Comment by JJ** [comment]
Si tenéis algún problema con los certificados, no tenéis más que avisar.
